### 회원가입
POST http://localhost:3000/user/join
Content-Type: application/json

{
  "userId":"test1",
  "nickName":"nickname",
  "password":"password1",
  "email":"email@naver.com",
  "address":"한국 서울"
}

### 로그인
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "userId": "userId1",
  "password": "password1"
}

### 중복체크



# ========================================================

### 상품 등록(admin)
POST http://localhost:3000/product
Content-Type: application/json

{
    "productImage": "wine.img",
    "productName": "레드와인",
    "price": 30000,
    "desc": "캬",
    "category": "와인",
    "delivery": "샛별 배송"
}

### 전체 상품 조회
GET http://localhost:3000/product


### 상품 삭제
DELETE http://localhost:3000/product/3

### 특정 상품 상세 조회
GET http://localhost:3000/product/4

### 카테고리 상품 상세 조회
GET http://localhost:3000/product/search/과일

# ========================================================

### 장바구니 조회
GET http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VySWQxIiwibmlja05hbWUiOiJuaWNrbmFtZSIsImVtYWlsIjoiZW1haWxAbmF2ZXIuY29tIiwiaWF0IjoxNjYxMTI5ODIzLCJleHAiOjE2NjEzMDI2MjN9.WrTlJtXfbR6n1_QHArpvkyQuGy9XQCTnGmtHuP7nu5E

### 장바구니 등록, 갯수 수정
POST http://localhost:3000/cart/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VySWQxIiwibmlja05hbWUiOiJuaWNrbmFtZSIsImVtYWlsIjoiZW1haWxAbmF2ZXIuY29tIiwiaWF0IjoxNjYxMTI5ODIzLCJleHAiOjE2NjEzMDI2MjN9.WrTlJtXfbR6n1_QHArpvkyQuGy9XQCTnGmtHuP7nu5E

{
    "quantity": 3
}

### 장바구니 삭제
DELETE http://localhost:3000/cart/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VySWQxIiwibmlja05hbWUiOiJuaWNrbmFtZSIsImVtYWlsIjoiZW1haWxAbmF2ZXIuY29tIiwiaWF0IjoxNjYxMTI5ODIzLCJleHAiOjE2NjEzMDI2MjN9.WrTlJtXfbR6n1_QHArpvkyQuGy9XQCTnGmtHuP7nu5E