### 회원가입
POST http://localhost:3000/user/join
Content-Type: application/json

{
  "userId":"test738",
  "nickName":"nicknam1",
  "password":"password1",
  "email":"email@naver.com",
  "address":"한국 서울"
}

### 로그인
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "userId": "test1",
  "password": "password1"
}

### 중복체크



# ========================================================

### 상품 등록(admin)
POST http://localhost:3000/product
Content-Type: application/json

{
    "productImage": "wine.img",
    "productName": "레드와인",
    "price": 30000,
    "desc": "캬",
    "category": "와인",
    "delivery": "샛별 배송"
}

### 전체 상품 조회
GET http://localhost:3000/product

### 상품 삭제
DELETE http://localhost:3000/product/3

### 특정 상품 상세 조회
GET http://localhost:3000/product/1

### 카테고리 상품 상세 조회
GET http://localhost:3000/product/search/와인

# ========================================================

### 장바구니 조회
GET http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ0ZXN0MSIsIm5pY2tOYW1lIjoibmlja25hbWUiLCJlbWFpbCI6ImVtYWlsQG5hdmVyLmNvbSIsImFkZHJlc3MiOiLtlZzqta0g7ISc7Jq4IiwiaWF0IjoxNjYxMTU0OTcxLCJleHAiOjE2NjEzMjc3NzF9.mXDqATiESIoyFfNQ57ub-j3gSoeoROJ3EQ2U3xNj2Wk


### 장바구니 등록, 갯수 수정
POST http://localhost:3000/cart/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ0ZXN0MSIsIm5pY2tOYW1lIjoibmlja25hbWUiLCJlbWFpbCI6ImVtYWlsQG5hdmVyLmNvbSIsImFkZHJlc3MiOiLtlZzqta0g7ISc7Jq4IiwiaWF0IjoxNjYxMTU0OTcxLCJleHAiOjE2NjEzMjc3NzF9.mXDqATiESIoyFfNQ57ub-j3gSoeoROJ3EQ2U3xNj2Wk


{
    "quantity": 1
}

### 장바구니 삭제
DELETE http://localhost:3000/cart/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ0ZXN0MSIsIm5pY2tOYW1lIjoibmlja25hbWUiLCJlbWFpbCI6ImVtYWlsQG5hdmVyLmNvbSIsImFkZHJlc3MiOiLtlZzqta0g7ISc7Jq4IiwiaWF0IjoxNjYxMTU0ODk1LCJleHAiOjE2NjEzMjc2OTV9.2kkzqftmI40RJGxmP3UpYd5zyEy2Y_w-JdvnNc61Xhc